
x-gpu-config:
  &gpu-config
  runtime: nvidia
  environment:
    - USER
    - DISPLAY=${DISPLAY:?err}
    - NVIDIA_VISIBLE_DEVICES=all
    - NVIDIA_DRIVER_CAPABILITIES=all

x-cpu-config:
  &cpu-config
  environment:
    - USER
    - DISPLAY=${DISPLAY:?err}

services:
  gz_turtlebot:
    # image: ros:humble-desktop 
    build:
      context: ..
      dockerfile: docker/Dockerfile.simulation
    <<: [ *cpu-config]
    container_name: gz_turtlebot
    network_mode: host
    ipc: host
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ./src:/ros2_ws/src
      # - ./docker_ws:/ros_ws/src
    # command: tail -f /dev/null
    command: >
          bash -c "source /opt/ros/humble/setup.bash &&
                   source install/setup.bash &&
                   ros2 launch armmy_turtlebot3 gzsim_turtlebot3.launch.py"
