
x-gpu-config:
  &gpu-config
  runtime: nvidia
  environment:
    - USER
    - DISPLAY=${DISPLAY:?err}
    - NVIDIA_VISIBLE_DEVICES=all
    - NVIDIA_DRIVER_CAPABILITIES=all

x-cpu-config:
  &cpu-config
  environment:
    - USER
    - DISPLAY=${DISPLAY:?err}
    - XDG_RUNTIME_DIR=${XDG_RUNTIME_DIR}
    - FASTDDS_BUILTIN_TRANSPORTS=UDPv4
    - RMW_IMPLEMENTATION=rmw_fastrtps_cpp
    # - RMW_IMPLEMENTATION=rmw_cyclonedds_cpp
  devices:
    - /dev/dri

services:
  gz_turtlebot:
    # image: ros:humble-desktop 
    build:
      context: ..
      dockerfile: docker/Dockerfile.simulation
    <<: [ *cpu-config]
    container_name: gz_turtlebot
    network_mode: host
    ipc: host
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ../src/armmy_simulation:/ros2_ws/src
      # - ./docker_ws:/ros_ws/src
    # command: tail -f /dev/null
    command: >
          bash -c "source /opt/ros/humble/setup.bash &&
                   colcon build --symlink-install &&
                   source install/setup.bash &&
                   ros2 launch armmy_turtlebot3 gzsim_turtlebot3.launch.py"
  rviz:
    image: osrf/ros:humble-desktop
    # build:
    #   context: ..
    #   dockerfile: docker/Dockerfile.simulation
    <<: [ *cpu-config]
    container_name: rviz2
    network_mode: host
    ipc: host
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
    # command: tail -f /dev/null
    command: rviz2
